spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bloodbank
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: prometheus
      password: prometheus

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: mitrogol

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
