spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bloodbank
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ikiakus@gmail.com
    password: cpxdcrzilhkewvbj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: mitrogol
